### ISSUE TITLE
[0.16.0beta1] Segfault when using MIDI-Learn

### ISSUE THREAD

**Issue by terencode** [monocasual/giada#255]
I don't know if I'm doing things right but it shouldn't crash anyway I guess:
1.  Set Config > MIDI > System to JACK or ALSA
2. Add your midi device to the input port
3. Save and restart giada
4. Go to edit > Setup Global MIDI Input
5. Click on "learn" and Giada will crash when you send a CC event with the MIDI device connected to giada input. 

Stack trace:
```
Thread 26 "giada" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4ff9700 (LWP 162289)]
giada::c::io::midiLearn (e=..., param=..., channelId=0) at src/glue/io.cpp:119
119		if (!m::model::get(m::model::channels, channelId).isMidiInAllowed(e.getChannel()))
(gdb) bt
#0  giada::c::io::midiLearn (e=..., param=..., channelId=0) at src/glue/io.cpp:119
#1  0x000055555562c292 in giada::v::geMidiLearner::<lambda(giada::m::MidiEvent)>::operator() (__closure=<optimized out>, e=...) at src/gui/elems/midiLearner.cpp:111
#2  std::_Function_handler<void(giada::m::MidiEvent), giada::v::geMidiLearner::cb_button()::<lambda(giada::m::MidiEvent)> >::_M_invoke(const std::_Any_data &, giada::m::MidiEvent &&) (__functor=..., __args#0=...)
    at /usr/include/c++/9.2.0/bits/std_function.h:300
#3  0x00005555555f6d4c in std::function<void (giada::m::MidiEvent)>::operator()(giada::m::MidiEvent) const (__args#0=..., this=0x555555a63ea0 <giada::m::midiDispatcher::(anonymous namespace)::learnCb_>)
    at /usr/include/c++/9.2.0/bits/std_function.h:685
#4  giada::m::midiDispatcher::dispatch (byte1=<optimized out>, byte2=<optimized out>, byte3=<optimized out>) at src/core/midiDispatcher.cpp:306
#5  0x00007ffff7929d5a in ?? () from /usr/lib/librtmidi.so.5
#6  0x00007ffff7c222aa in ?? () from /usr/lib/libjack.so.0
#7  0x00007ffff7c21a08 in ?? () from /usr/lib/libjack.so.0
#8  0x00007ffff7c3ab1d in ?? () from /usr/lib/libjack.so.0
#9  0x00007ffff7b114cf in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007ffff742d2d3 in clone () from /usr/lib/libc.so.6
```

Related to #181 ?

---
- giada v0.16.0beta1.r12.gc747cc1f
- ArchLinux

**Comment by monocasual** [comment]
Thanks for reporting. This is the new UI<->Engine architecture which needs a little work.
