### ISSUE TITLE
SEGV

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#670]
**Environment**
- OS: FreeBSD 13.2
- Giada version: 0.26.0

**Describe the bug**
```
JackClient::AcquireSelfRealTime error
[New LWP 344659 of process 19233]
[New LWP 344660 of process 19233]
Cannot use real-time scheduling (RR/5) (1: Operation not permitted)
JackClient::AcquireSelfRealTime error
[New LWP 344661 of process 19233]
[New LWP 344662 of process 19233]
XOpenIM() failed
[Detaching after fork from child process 19237]
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[Detaching after fork from child process 19240]
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[Detaching after fork from child process 19243]
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[Detaching after fork from child process 19246]
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[Detaching after fork from child process 19249]
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Assertion failed: (index < m_ids.size()), function showItem, file /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/basics/choice.cpp, line 136.
(gdb) bt
Thread 1 received signal SIGABRT, Aborted.
Sent by thr_kill() from pid 19233 and user 1001.
0x00000008021aefda in thr_kill () from /lib/libc.so.7

#0  0x00000008021aefda in thr_kill () from /lib/libc.so.7
#1  0x0000000802128b44 in raise () from /lib/libc.so.7
#2  0x00000008021d8699 in abort () from /lib/libc.so.7
#3  0x000000080210beb1 in __assert () from /lib/libc.so.7
#4  0x0000000000d2f23f in giada::v::geChoice::showItem (this=0x802ceb800, id=0) at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/basics/choice.cpp:136
#5  0x0000000000ceaa00 in giada::v::geTabMidi::rebuild (this=0x802cee700, data=...) at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/config/tabMidi.cpp:175
#6  0x0000000000ce9f0b in giada::v::geTabMidi::geTabMidi (this=0x802cee700, bounds=...) at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/config/tabMidi.cpp:163
#7  0x0000000000bb1d3b in giada::v::gdConfig::gdConfig (this=0x802ccb400, w=400, h=370, model=...) at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/dialogs/config.cpp:57
#8  0x0000000000b739c1 in giada::c::layout::openConfigWindow () at /usr/ports/audio/giada/work/giada-0.26.0/src/glue/layout.cpp:133
#9  0x0000000000c8d9c1 in giada::v::geMainMenu::geMainMenu()::$_3::operator()() const (this=0x802c8ca28)
    at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/mainWindow/mainMenu.cpp:84
#10 0x0000000000c8d9a5 in std::__1::__invoke[abi:v160006]<giada::v::geMainMenu::geMainMenu()::$_3&>(giada::v::geMainMenu::geMainMenu()::$_3&) (__f=...)
    at /usr/include/c++/v1/__functional/invoke.h:394
#11 0x0000000000c8d965 in std::__1::__invoke_void_return_wrapper<void, true>::__call<giada::v::geMainMenu::geMainMenu()::$_3&>(giada::v::geMainMenu::geMainMenu()::$_3&) (__args=...)
    at /usr/include/c++/v1/__functional/invoke.h:487
#12 0x0000000000c8d93d in std::__1::__function::__alloc_func<giada::v::geMainMenu::geMainMenu()::$_3, std::__1::allocator<giada::v::geMainMenu::geMainMenu()::$_3>, void ()>::operator()[abi:
v160006]() (this=0x802c8ca28) at /usr/include/c++/v1/__functional/function.h:185
#13 0x0000000000c8cbe9 in std::__1::__function::__func<giada::v::geMainMenu::geMainMenu()::$_3, std::__1::allocator<giada::v::geMainMenu::geMainMenu()::$_3>, void ()>::operator()() (
    this=0x802c8ca20) at /usr/include/c++/v1/__functional/function.h:356
#14 0x00000000009f1bd2 in std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const (this=0x802c8ca20) at /usr/include/c++/v1/__functional/function.h:510
#15 0x00000000009f1b55 in std::__1::function<void ()>::operator()() const (this=0x802c8ca20) at /usr/include/c++/v1/__functional/function.h:1156
#16 0x0000000000d24a95 in giada::v::geButton::handle (this=0x802c8c9a0, e=2) at /usr/ports/audio/giada/work/giada-0.26.0/src/gui/elems/basics/button.cpp:67
#17 0x00000000016ccfa4 in send_event (event=2, to=0x802c8c9a0, window=0x802c32400) at /usr/ports/audio/giada/work/giada-0.26.0/src/deps/fltk/src/Fl.cxx:1194
```

clang-16

**Comment by gvnnz** [comment]
Thanks for reporting @yurivict, a fix is underway.

**Comment by gvnnz** [comment]
Done in 5f5de07de3bf0fed23802d4a491d48bc578a8b63, closing.

**Comment by luzpaz** [comment]
This was blocking building giada on FreeBSD
